
modLoader="javafml" #mandatory
loaderVersion="[34,)" #mandatory
issueTrackerURL="https://github.com/MaxNeedsSnacks/Interactio/issues" #optional
license="The MIT License (MIT)"

[[mods]] #mandatory
modId="interactio" #mandatory
version="${version}" #mandatory
displayName="Interactio" #mandatory
# updateJSONURL="http://myurl.me/" #optional
# displayURL="http://example.com/" #optional
# logoFile="" #optional
# credits="" #optional
authors="MaxNeedsSnacks" #optional
description='''
Adds various different kinds of in-world crafting recipes to the game.
'''

[[dependencies.interactio]] #optional
    modId="forge" #mandatory
    mandatory=true #mandatory
    versionRange="[34,)" #mandatory
    ordering="NONE"
    side="SERVER"

[[dependencies.interactio]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.16.3,)"
    ordering="NONE"
    side="SERVER"

[[dependencies.interactio]]
    modId = "architectury"
    mandatory = true
    versionRange = "[1.2,)"
    ordering = "AFTER"
    side = "BOTH"