
modLoader="javafml" #mandatory
loaderVersion="[33,)" #mandatory
# issueTrackerURL="http://my.issue.tracker/" #optional
license="The MIT License (MIT)"

[[mods]] #mandatory
modId="interactio" #mandatory
version="${file.jarVersion}" #mandatory
displayName="Interactio" #mandatory
# updateJSONURL="http://myurl.me/" #optional
# displayURL="http://example.com/" #optional
# logoFile="" #optional
# credits="" #optional
authors="MaxNeedsSnacks" #optional
description='''
Adds various different kinds of in-world crafting recipes to the game.
'''

[[dependencies.interactio]] #optional
    modId="forge" #mandatory
    mandatory=true #mandatory
    versionRange="[33.0.0,)" #mandatory
    ordering="NONE"
    side="BOTH"

[[dependencies.interactio]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.16.2,)"
    ordering="NONE"
    side="BOTH"
